name: DevOps CICD Pipeline

on: push

jobs:
  devops-ci:
    runs-on: ubuntu:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    - name: Docker Registry login
      uses: docker/login-action@v3.5.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.18.0
      with:
        file: ./Dockerfile
        tags: yogeshraheja/devopspython:$GITHUB_RUN_ID
        
