name: DevOps CICD Pipeline

on: 
  push:
    branches:
      - main
    paths-ignore:
      - ./manifests

jobs:
  devops-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    - name: Docker Registry login
      uses: docker/login-action@v3.5.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.18.0
      with:
        file: ./Dockerfile
        tags: yogeshraheja/devopspython:${{ github.sha }}
        push: true
    - name: Updating image tag inside manifest file
      run: |
        pip install yq
        yq -Yi '.spec.template.spec.containers[0].image = "yogeshraheja/devopspython:${{ github.sha }}"' ./manifests/02_devopsdep.yaml
    - name: Commit and Push the code
      run: |
        git config user.name "Yogesh Raheja"
        git config user.email "yogesh.raheja@thinknyx.com"
        git commit -am "Updating image tag inside manifest file using Actions"
        git push







